const actionType = {
    GET_HOURLY_DATA_PROGRESS: 'GET_HOURLY_DATA_PROGRESS',
    GET_HOURLY_DATA_SUCCEED: 'GET_HOURLY_DATA_SUCCEED',
    GET_HOURLY_DATA_FAIL: 'GET_HOURLY_DATA_FAIL',
    MAKE_ISERROR_FALSE: 'MAKE_ISERROR_FALSE'

}

export default actionType;