const actionType = {
    GET_HOURLY_DATA_PROGRESS: 'GET_HOURLY_DATA_PROGRESS',
    GET_HOURLY_DATA_SUCCEED: 'GET_HOURLY_DATA_SUCCEED',
    GET_HOURLY_DATA_UPDATE: 'GET_HOURLY_DATA_UPDATE',
    GET_HOURLY_DATA_FLAG_FALSE: 'GET_HOURLY_FLAG_FALSE',
    GET_HOURLY_DATA_FAIL: 'GET_HOURLY_DATA_FAIL',
    MAKE_ISERROR_FALSE: 'MAKE_ISERROR_FALSE',

    GET_WEEKLY_DATA_PROGRESS: 'GET_WEEKLY_DATA_PROGRESS',
    GET_WEEKLY_DATA_SUCCEED: 'GET_WEEKLY_DATA_SUCCEED',
    GET_WEEKLY_DATA_FAIL: 'GET_WEEKLY_DATA_FAIL',


    GET_REALTIME_DATA:'GET_REALTIME_DATA',
    GET_REALTIME_DATA_SUCCEED:'GET_REALTIME_DATA_SUCCEED',
    GET_REALTIME_DATA_UPDATE:'GET_REALTIME_DATA_UPDATE',
    GET_REALTIME_DATA_FAIL:'GET_REALTIME_DATA_FAIL'

}

export default actionType;