const actionType = {
    GET_HOURLY_DATA_PROGRESS: 'GET_HOURLY_DATA_PROGRESS',
    GET_HOURLY_DATA_SUCCEED: 'GET_HOURLY_DATA_SUCCEED',
    GET_HOURLY_DATA_UPDATE: 'GET_HOURLY_DATA_UPDATE',
    GET_HOURLY_DATA_FLAG_FALSE: 'GET_HOURLY_FLAG_FALSE',
    GET_HOURLY_DATA_FAIL: 'GET_HOURLY_DATA_FAIL',
    MAKE_ISERROR_FALSE: 'MAKE_ISERROR_FALSE',

    GET_WEEKLY_DATA_PROGRESS: 'GET_WEEKLY_DATA_PROGRESS',
    GET_WEEKLY_DATA_SUCCEED: 'GET_WEEKLY_DATA_SUCCEED',
    GET_WEEKLY_DATA_FAIL: 'GET_WEEKLY_DATA_FAIL',


    GET_REALTIME_DATA:'GET_REALTIME_DATA',
    GET_REALTIME_DATA_SUCCEED:'GET_REALTIME_DATA_SUCCEED',
    GET_REALTIME_DATA_UPDATE:'GET_REALTIME_DATA_UPDATE',
    GET_REALTIME_DATA_FAIL:'GET_REALTIME_DATA_FAIL',

    LOAD_BRANCHES : 'LOAD_BRANCHES',
    LOAD_BRANCHES_SUCCEED: 'LOAD_BRANCHES_SUCCEED',
    LOAD_BRANCHES_FAIL: 'LOAD_BRANCHES_FAIL',


    SET_CURRENT_BRANCH: 'SET_CURRENT_BRANCH',


    SIGNIN_PROG: "SIGNIN_PROG",
    SIGNIN_ERROR: "SIGNIN_ERROR",
    SIGNIN_SUCC: "SIGNIN_SUCC",

    SIGNUP_PROG: "SIGNUP_PROG",
    SIGNUP_ERROR: "SIGNUP_ERROR",
    SIGNUP_SUCC: "SIGNUP_SUCC",


    UPDATE_USER_PRO: "UPDATE_USER_PRO",

    CHECK_USER_PROG: "CHECK_USER_PROG",
    CHECK_USER_SUCC: "CHECK_USER_SUCC",
    SIGNOUT_PROG: "SIGNOUT_USER_PROG",
    SIGNOUT_SUCC: "SIGNOUT_USER_SUCC",
    SIGNOUT_ERROR: "SIGNOUT_USER_ERROR",

    INCREMENT_ITERATION:'INCREMENT_ITERATION',
    RESET_ITERATION:'RESET_ITERATION',

    GET_CURRENT_DATE_PROGRESS:'GET_CURRENT_DATE_PROGRESS',
    GET_CURRENT_DATE_SUCCEED:'GET_CURRENT_DATE_SUCCEED',
    GET_CURRENT_DATE_FAIL:'GET_CURRENT_DATE_FAIL',

    GET_DATA_DATE_WISE_PROGRESS: 'GET_DATA_DATE_WISE_PROGRESS',
    GET_DATA_DATE_WISE_SUCCEED: 'GET_DATA_DATE_WISE_SUCCEED',
    GET_DATA_DATE_WISE_FAIL: 'GET_DATA_DATE_WISE_FAIL',
    CLEAR_MONTHLY_ARRAY: 'CLEAR_MONTHLY_ARRAY',
    CLEAR_WEEKLY_ARRAY: 'CLEAR_WEEKLY_ARRAY'

}

export default actionType;